name: dstu-gost-coverage

on:
  push:
    branches:
      - master
      - develop
    paths:
      - packages/dstu-gost
      - !packages
  pull_request:
    branches:
      - master
      - develop
    paths:
      - packages/dstu-gost
      - !packages

jobs:
  coverage:
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install, build
        run: |
          npm install
          npm run build --if-present
      - name: npm run check
        run: npm run check
      - name: npm run test:cov
        run: npm run test:cov
