name: dstu-gost

on:
  push:
    branches:
      - master
      - develop
    paths:
      - packages/dstu-gost
      - !packages
  pull_request:
    branches:
      - master
      - develop
    paths:
      - packages/dstu-gost
      - !packages

jobs:
  build:
    env:
      CI: true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build
        run: |
          npm install
          npm run build --if-present
      - name: npm run check
        run: npm run check
      - name: npm test
        run: npm test


